# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

development:
  STRIPE_SECRET_KEY: sk_test_e2Jyqc84D52dW381fNpkCo4i
  STRIPE_PUBLISHABLE_KEY: pk_test_8IBxaUpEIJM9WZR5OzPKN3U7

test:
  STRIPE_SECRET_KEY: sk_test_e2Jyqc84D52dW381fNpkCo4i
  STRIPE_PUBLISHABLE_KEY: pk_test_8IBxaUpEIJM9WZR5OzPKN3U7

production:
  S3_KEY: AKIAJ2X2DS3JUWML46ZA
  S3_SECRET: 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
  S3_BUCKET_NAME: myflix-jy124
  S3_ASSET_URL: https://s3.amazonaws.com
# test on heroku
  STRIPE_SECRET_KEY: sk_test_e2Jyqc84D52dW381fNpkCo4i
  STRIPE_PUBLISHABLE_KEY: pk_test_8IBxaUpEIJM9WZR5OzPKN3U7

#  STRIPE_SECRET_KEY: sk_live_618ADxWE1eUUHDzDHN0W5o5R
#  STRIPE_PUBLISHABLE_KEY: pk_live_uvvA2ZTR4x1IoEY1XPesVLcr